---
- name: Install PrinceXML
  apt:
    deb: "{{ prince_package_uri }}"
    state: present

- name: Upload PrinceXML license
  copy:
    src: "{{ prince_license }}"
    dest: /usr/lib/prince/license/license.dat.new
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: prince_license != ""

- name: Check for existing PrinceXML license
  stat:
    path: /usr/lib/prince/license/license.dat
  register: existing_license
  when: prince_license != ""

- name: Backup old PrinceXML license
  command: mv /usr/lib/prince/license/license.dat /usr/lib/prince/license/license.dat.{{ lookup('pipe', 'date +%Y%m%d') }}.old
  when: existing_license.stat.exists and prince_license != ""

- name: Install new PrinceXML license
  command: mv /usr/lib/prince/license/license.dat.new /usr/lib/prince/license/license.dat
  when: prince_license != ""
